Calebfeliciano/The-Barkives

- README.md
- client/package-lock.json
- package-lock.json
- package.json
- server/.env.EXAMPLE
- server/package-lock.json
Add dist in package.json and add README template.
> Edit package.json and readme template

- server/src/config/connection.ts
I've changed the database name.
> Changed database name

- client/src/components/Navbar.tsx
- client/src/main.tsx
- client/src/pages/Healthcare.tsx
- client/src/pages/Services.tsx
Edit the routes in the main.tsx and add the necessary pages for the website
> Edit the routes and add pages

- client/src/main.tsx
- client/src/pages/Home.tsx
- client/src/pages/SavedPets.tsx
> Minor file changes

- client/src/main.tsx
- client/src/pages/Home.tsx
- client/src/pages/SavedPets.tsx
Reverts Calebfeliciano/The-Barkives#10
> Revert "Minor file changes"

- client/src/models/User.ts
- client/src/pages/SavedPets.tsx
- client/src/utils/mutations.ts
- client/src/utils/queries.ts
Made changes to a few client-side files.
> Client-side file changes

- client/src/pages/Services.tsx
Added the basics to the service page. Need to add a delete function and a schedule function
> Started Service page

- client/src/utils/mutations.ts
- client/src/utils/queries.ts
- server/src/models/Pet.ts
- server/src/schemas/typeDefs.ts
- server/src/server.ts
- server/src/services/auth-service.ts
> Minor fixes to queries and mutations

- client/src/App.tsx
- server/src/schemas/typeDefs.ts
Update the remove pet function to fix warning when removing pets
> Update remove pet function

- client/src/App.tsx
- client/src/components/RemovePet.tsx
Fix error when removing pets while still allowing the user to add pets
> Fix error when removing pets

- client/src/components/Navbar.tsx
Change which nav tabs are displayed when a user is logged in or is not logged in
> Update nav tabs when logged in

- client/src/components/CollarWithTag.tsx
- client/src/components/PetCarousel.tsx
- client/src/components/PetInfo.tsx
- client/src/components/SelectPet.tsx
- client/src/components/SwingingTag.tsx
- client/src/main.tsx
- client/src/models/Pets.ts
- client/src/pages/Home.tsx
- client/src/pages/SavedPets.tsx
- client/src/styles/Collar.css
- client/src/styles/index.css
I've added new components for the select pet feature.
> Added new components

- client/src/components/AddPet.tsx
- client/src/models/Pets.ts
- client/src/pages/Healthcare.tsx
- client/src/utils/queries.ts
- server/src/interfaces/PetInput.ts
- server/src/models/Pet.ts
- server/src/schemas/typeDefs.ts
Add the healthcare info for pets and the code for the healthcare page
> Add healthcare info for pets

- client/src/components/PetCarousel.tsx
- client/src/components/SelectPet.tsx
- client/src/main.tsx
- server/src/schemas/resolvers.ts
Added select pet functionality
> Added select pet functionality

- client/src/components/SelectPet.tsx
- client/src/pages/Healthcare.tsx
- package.json
Show the healthcare for the selected pet when the user navigates to the Healthcare tab
> Add healthcare for selected pet

- client/src/components/LoginForm.tsx
- client/src/components/SignupForm.tsx
- server/src/schemas/resolvers.ts
Add error checking when a user logs in or signs up, including invalid email address, invalid log in information, username already taken, and email already taken.
> Add error checking for login/signup

- client/package-lock.json
- client/package.json
- client/src/components/PetCard.tsx
- client/src/components/PetCarousel.tsx
- client/src/components/PetInfo.tsx
- client/src/components/SelectPet.tsx
- client/src/pages/SavedPets.tsx
- client/src/styles/PetCard.css
- client/src/styles/PetCarousel.css
- client/src/styles/index.css
- package-lock.json
> Styling changes

- client/package-lock.json
- client/package.json
- client/src/components/CollarWithTag.tsx
- client/src/components/PetCarousel.tsx
- client/src/styles/Collar.css
- client/src/styles/PetCarousel.css
> Updated syles

- client/src/main.tsx
- client/src/pages/Calendar.tsx
- client/src/styles/Calendar.css
- client/src/utils/auth.ts
- client/src/utils/mutations.ts
- client/src/utils/queries.ts
- server/src/models/Appointment.ts
- server/src/models/index.ts
- server/src/schemas/resolvers.ts
- server/src/schemas/typeDefs.ts
Add Calendar, including the style sheet and typeDefs, resolvers, mutations, and queries for adding events
> Add calendar page

- client/src/App.tsx
- client/src/components/AddPet.tsx
- client/src/components/LoginForm.tsx
- client/src/components/Navbar.tsx
- client/src/components/PetCarousel.tsx
- client/src/components/RemovePet.tsx
- client/src/components/SignupForm.tsx
- client/src/pages/Healthcare.tsx
- client/src/pages/Home.tsx
- client/src/pages/SavedPets.tsx
- client/src/styles/Collar.css
- client/src/styles/HomePage.css
- client/src/styles/PetCard.css
- client/src/styles/SavedPets.css
- client/src/styles/index.css
- client/src/styles/modal.css
- package-lock.json
- package.json
I've made some updates to the styles.
> Updated styles

- server/src/server.ts
- server/src/services/auth-service.ts
updated, server.ts and auth-services.ts in preparation for render deploy
> preparing for render deploy

- client/src/components/Navbar.tsx
- client/src/pages/Services.tsx
- client/src/styles/HealthcarePage.css
- client/src/styles/ServicesPage.css
- client/src/styles/index.css
- client/src/styles/modal.css
> Styles update

- client/src/pages/Calendar.tsx
- client/src/styles/Calendar.css
- client/src/utils/mutations.ts
- server/src/schemas/resolvers.ts
- server/src/schemas/typeDefs.ts
- server/src/server.ts
- server/src/services/auth-service.ts
Revert the auth and server files
> Edit server and auth files

- server/src/server.ts
Add directory name declaration
> Add dirname

- server/src/server.ts
> Add filename declaration

- server/src/server.ts
> Add path to directory

- client/.env.EXAMPLE
- client/src/App.tsx
- client/tsconfig.json
- client/vite-env.d.ts
- server/src/server.ts
Add vite configuration for Render deployment
> Add vite config

- client/src/App.tsx
Update the modal settings to allow the user to log in on the home page button or using the login/signup navtab
> Update modal settings

- client/src/styles/HomePage.css
Edit the styling for the login box to put it in the middle of the page
> Edit login box styling
